core/dumpvar.mk

This got dropped after caf-rebase and was missed in
010ce6f3a21c73d1eb86c4558974d83e5edf5d5a
Change-Id: I1a0d18e3c3c7b27a3e0d2590caec498e77bfeca6

Add dumpvar for WITH_GMS

---

core/Makefile

Actually there are some devices with strange recovery image handling that don't use full recovery image,
but require recovery.img in BOOTABLE_IMAGES for proper patch generation.
Change-Id: I206ac4d477577a5264533d55d1fec24129fd0ee8

build: always copy recovery.img to BOOTABLE_IMAGES.

---

core/definitions.mk
core/package_internal.mk

Building with LOCAL_STATIC_ANDROID_LIBARIES and LOCAL_USE_APPT2
causes a warning:
build/core/package_internal.mk:143: Empty argument supplied to find-subdir-assets
Only call find-subdir-assets if my_res_dir is not empty.
Also improve the warning message to make it easier to find the module
that caused it.
Test: m -j
Change-Id: I9a71162c7e2ed82f64d6844baca256968ac77317

Fix warning with AAPT2 and LOCAL_STATIC_ANDROID_LIBRARIES

---

core/config.mk

* hardware/ril is a required project for any build. Since
pathmap logic is available to any project building out of
a Lineage checkout, RIL path mapping should be made
available to all build types.
Change-Id: I45fd8771d0226caaf5ac05899fbbdb73a9cc8c01

pathmap: Move RIL path mapping to core/config.mk

---

core/Makefile

For now, vendor build properties are added into /system/build.prop
when property split isn't enabled.
So we have the duplicate codes to add them to /system/build.prop and
/vendor/build.prop case by case.
But either /vendor/build.prop or /system/vendor/build.prop can exist
always.
So this CL will install $(TARGET_OUT_VENDOR)/build.prop always and
remove the duplication.
Bug: 68115808
Test: tested on aosp_x86-userdebug
Change-Id: Ic734418890629d011c733c2d8d14739275e64a78

Install (vendor|system/vendor)/build.prop always

---

core/Makefile

* This was mistakenly added in merging:
"Store the base64 release key in the OTA zips".
Change-Id: Ib62edffdc5bc1b769428e91677b8c4960b9e0904

build: Remove duplicate zip command

---

core/config.mk

* The prebuilt flex binary crashes due changes in newer glibc versions,
and the prebuilt bison binary doesn't work on newer Darwin versions.
* While this works for most of the usecases,
you shouldn't pollute your path with an older version of flex or bison,
and at the same time you shouldn't use the binary provided
by the host for compatibility reasons
-> Add a flag to allow the user to provide its own flex and bison binary,
that should match the version provided by AOSP.
Usage: Add `export FLEX_EXEC=$path_to_flex` in your .bashrc/.zshrc
Example: `export FLEX_EXEC=$HOME/android/flex-2.5.39`
Change-Id: I75f98372a221b48636f870a5b7984f0a779fa29d

Move away from USE_HOST flag and introduce $BINARY_EXEC

---

core/main.mk

* Our properties were supposed to go to /system/etc/prop.default
after the following commit:
"lineage: Move to Google's method of defining system default props"
Change-Id: I6cb0e28a7599b010b389cc541015a37010a00f4b
* However if BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED is not true,
only /default.prop will retain the properties contents of
ADDITIONAL_DEFAULT_PROPERTIES and PRODUCT_SYSTEM_DEFAULT_PROPERTIES,
and none of our versioning identification was held in the system
* Enabling BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED globally would
break all properties on devices that handle partitions usually
at the device level rather than the kernel due to mounting races
* Include the vendor/lineage/config/main.mk entrypoint to be allowed
to extend ADDITION_BUILD_PROPERTIES as we need to define our …

build: Include LineageOS specific properties in build.prop

---

core/config.mk
core/main.mk

* Include MTK/QCOM rules directly from
vendor/lineage/build/core/config.mk hook, since that is what it is
there for.
* Remove apicheck.mk hook, this is unused, and if it turns out to be
needed again, it can be included by the config.mk hook mentioned above.
* Place main.mk hook into vendor/lineage/build/core/main.mk with the
rest of the make build system hooks.
Change-Id: I51bda9f5d35a63113d6eab98e06da8919ba46480

build: Clean up makefile hook inclusions

---

core/binary.mk

Change-Id: I68b44fd1e868a3326a6ab1a7e5fe42b8eeecd1c1

core: Remove deprecated kernel header dependency path warning

---

core/Makefile

on some devices there is a vendor symlink in rootdir.
Ignore that for recovery.
Change-Id: Id0e54f7d135418cbe3adc1985c2dd26e260ab495

build: recovery: add vendor to exclusion list

---

target/product/core_base.mk

* This was a dependency of legacy NXP NFC stack, deprecated long ago.
The devices that are still using this stack are explicitly building
libnfc, which in turn has libnfc_ndef as shared lib.
Change-Id: Id3b859cdea00452f7d1ee21455e08fe342649a1e

core_base: Remove libnfc_ndef from PRODUCT_PACKAGES

---

core/Makefile

* $(hide) is a make construct, if $(call build-image-kernel-modules ...)
is run by shelling out within make, this breaks.
* Assume the caller of this function will always hide for it.
Change-Id: I5b56cf9ba76a1f69bcd96966883876381e61983a

build: Allow build-image-kernel-modules to be called from shell

---

core/definitions.mk

Makes pretty-error and pretty-warning behave more like $(error) and
$(warning), where you don't need to do things like quote parentheses.
Bug: 118833208
Test: trigger the private_apis && sdk set error in sdk_check.mk,
which no longer produces bash syntax errors
Change-Id: I766ff98ad4e652f59dbef9dd5654f1cd10a2d038

Quote message in echo-error/echo-warning macros

---

core/Makefile

Without the -d $(TARGET_OUT) option for mkbootfs, only the
compiled-in fs_config (from AOSP) is used for the generated
ramdisk image. Device-specific additions are ignored.
This is why AOSP sets this option for both the boot- and recovery
ramdisk [1]. However, the option was removed for the recovery ramdisk
in https://review.lineageos.org/c/LineageOS/android_build/+/222722
This causes device-specific fs_config additions to be ignored when
generating the recovery ramdisk, potentially setting the wrong
permissions.
[1]: https://android.googlesource.com/platform/build/+/refs/tags/android-9.0.0_r37/core/Makefile#1388
Change-Id: I0f77a49d8b2f08791e60b34ddbb6f3b32bc2f0bc

build: Respect fs_config when generating recovery ramdisk

---

tools/releasetools/sign_target_files_apks.py

Test: run cts -m CtsSecurityTestCases -t \
android.security.cts.PackageSignatureTest#testPackageSignatures
Bug: 145955635
Change-Id: I1a1498562e2b5983010cb98e3edcd03ceb2cce19
Signed-off-by: Oleh Cherpak <oleh.cherpak@globallogic.com>

sign_target_apks: Add networkstack to default key_map

---

core/build_rro_package.mk

Resource configs should not be deduped when building RROs since it
would be impossible to override some resource configs with the same
value as the default config. Also, aapt2 removes resources that do not
have default configurations. If an overlay attempts to overlay a
non-default configuration without overlaying the default, the resource
will be removed and the value will not be overlaid at all.
Bug: 146227008
Test: m-j
Change-Id: I1465b599cbf7f464d1b5b75a87e7dafa2cf734b0

Do not remove RRO resources

---

core/board_config.mk
target/product/updatable_apex.mk

When `OVERRIDE_TARGET_FLATTEN_APEX` is defined (e.g. set in the
environment), `TARGET_FLATTEN_APEX` is forcibly assigned its value.
This is useful to enable/disable APEX flattening from the command
line (thus ignoring the product's default configuration), for testing
purposes.
Note: Previously it was possible to set `TARGET_FLATTEN_APEX` directly
and have the same effect, but recent changes in the build
configuration now prevent that option.
Test: Check that:
export OVERRIDE_TARGET_FLATTEN_APEX=true \
&& . ./build/envsetup.sh \
&& lunch aosp_walleye-userdebug \
&& export OVERRIDE_TARGET_FLATTEN_APEX=true \
&& build/soong/soong_ui.bash --dumpvar-mode TARGET_FLATTEN_APEX
returns:
true
Bug: 121117762
Change-Id: Ib9ccae38430340de38e4758b4f55df2c65ea60d5

Introduce build variable `OVERRIDE_TARGET_FLATTEN_APEX`.

---

core/Makefile

* Backuptool is not exclusively used for GApps but
also used by other things (i.e. Magisk), hence
it shouldn't be disabled on all GMS builds.
Change-Id: Ia95c6fed21d7bed5e2e0610aa94264edc1d02c80

build: Disable backuptool on user instead of GMS builds

---

core/base_rules.mk

In the case of building a multilib library that defines LOCAL_VINTF_FRAGMENTS,
the previous code would create duplicate rules for the fragment. This change
uses the my_vintf_new_installed variable (which may be empty) to avoid the
duplication.
Bug: 139268165
Test: Verify that build warnings are gone, yet VINTF fragment still installed.
Change-Id: I579ec650019a29a6a105118ad5e5ae9376e8d9bc
(cherry picked from commit 6733381fceb44fe074e3586c7a94705c4d49a509)

Avoid adding VINTF manifest fragment more than once.
